cache:
  paths:
    - cached
stages:
  - build_iso


variables:
  KUBERNETES_CPU_REQUEST: 2
  KUBERNETES_CPU_LIMIT: 2
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi


build_iso:
  stage: build_iso
  image: ubuntu:focal
  script:
    - ./build.sh
  artifacts:
    paths:
      - artifacts/
    expire_in: 24 hours


