stages:
  - build_iso

build_iso:
  stage: build_iso
  image: ubuntu:focal
  script:
    - ./build.sh
    - "sha256sum artifacts/ubuntu-${CI_COMMIT_SHORT_SHA}.iso >> artifacts/hashes.txt"
    - "sha512sum artifacts/ubuntu-${CI_COMMIT_SHORT_SHA}.iso >> artifacts/hashes.txt"
  artifacts:
    paths:
      - artifacts/
    expire_in: 24 hours


