cache:
  paths:
    - cached
stages:
  - build_iso

build_iso:
  stage: build_iso
  image: ubuntu:focal
  script:
    - ./build.sh
    - ./build_usb_after_install_stick.sh
  artifacts:
    paths:
      - artifacts/
    expire_in: 24 hours


